import type { ComponentToken as SnugMenuComponentToken } from '../../snug-menu/style';
import type { ComponentToken as AudioCardComponentToken } from '../../audio-card/style';
import type { ComponentToken as ImageCardComponentToken } from '../../image-card/style';
import type { ComponentToken as VideoCardComponentToken } from '../../video-card/style';
import type { ComponentToken as FileCardComponentToken } from '../../file-card/style';
import type { ComponentToken as AudioViewerComponentToken } from '../../audio-viewer/style';
import type { ComponentToken as CloseComponentToken } from '../../close/style';
import type { ComponentToken as ColComponentToken } from '../../col/style';
import type { ComponentToken as RowComponentToken } from '../../row/style';
import type { ComponentToken as ContainerComponentToken } from '../../container/style';
import type { ComponentToken as ContextMenuComponentToken } from '../../context-menu/style';
import type { ComponentToken as DndSortComponentToken } from '../../dnd-sort/style';
import type { ComponentToken as EditorComponentToken } from '../../editor/style';
import type { ComponentToken as FormComponentToken } from '../../form/style';
import type { ComponentToken as FormListComponentToken } from '../../form-list/style';
import type { ComponentToken as FormQueryComponentToken } from '../../form-query/style';
import type { ComponentToken as HighlightComponentToken } from '../../highlight/style';
import type { ComponentToken as IconComponentToken } from '../../icon/style';
import type { ComponentToken as LongTextComponentToken } from '../../long-text/style';
import type { ComponentToken as MaskComponentToken } from '../../mask/style';
import type { ComponentToken as PanelComponentToken } from '../../panel/style';
import type { ComponentToken as ScrollViewComponentToken } from '../../scroll-view/style';
import type { ComponentToken as TableComponentToken } from '../../table/style';
import type { ComponentToken as TableColumnComponentToken } from '../../table/table-column/style';
import type { ComponentToken as TableColumnEditorComponentToken } from '../../table/table-column-editor/style';
import type { ComponentToken as TableExportComponentToken } from '../../table/table-export/style';
import type { ComponentToken as TableActionComponentToken } from '../../table-action/style';
import type { ComponentToken as UploadComponentToken } from '../../upload/style';
import type { ComponentToken as VideoViewerComponentToken } from '../../video-viewer/style';
import type { ComponentToken as TransitionGroupComponentToken } from '../../transition-group/style';

export interface ComponentTokenMap {
  SnugMenu?: SnugMenuComponentToken;
  AudioCard?: AudioCardComponentToken;
  ImageCard?: ImageCardComponentToken;
  VideoCard?: VideoCardComponentToken;
  FileCard?: FileCardComponentToken;
  AudioViewer?: AudioViewerComponentToken;
  Close?: CloseComponentToken;
  Col?: ColComponentToken;
  Row?: RowComponentToken;
  Container?: ContainerComponentToken;
  ContextMenu?: ContextMenuComponentToken;
  DndSort?: DndSortComponentToken;
  Editor?: EditorComponentToken;
  Form?: FormComponentToken;
  FormList?: FormListComponentToken;
  FormQuery?: FormQueryComponentToken;
  Highlight?: HighlightComponentToken;
  Icon?: IconComponentToken;
  LongText?: LongTextComponentToken;
  Mask?: MaskComponentToken;
  Panel?: PanelComponentToken;
  ScrollView?: ScrollViewComponentToken;
  Table?: TableComponentToken;
  TableColumn?: TableColumnComponentToken;
  TableColumnEditor?: TableColumnEditorComponentToken;
  TableExport?: TableExportComponentToken;
  TableAction?: TableActionComponentToken;
  Upload?: UploadComponentToken;
  VideoViewer?: VideoViewerComponentToken;
  TransitionGroup?: TransitionGroupComponentToken;
}
